export const RESPONSE_TYPE = {
    SUCCESS: "Success",
    ERROR: "Error",
};

export const ERROR_MESSAGE = {
    INACTIVE_ACCOUNT: "Your account is inactivated. Please contact support team.",
    ROLE_EXISTS: "this Role Already exists",
    ROLE_NOT_FOUND: "Role not found",
    FORBIDDEN_REQUEST: "Forbidden Access",
    CONTACT_NOT_FOUND: "Contact not found",
    PERMISSION_EXISTS: "Permission exists",
    PERMISSION_NOT_FOUND: "Permission not found",
    COUPON_EXISTS: "Coupon exist",
    COUPON_EXIST: "Course with this name already  exist",
    COUPON_NOT_EXISTS: "Coupon does not exist",
    ADMIN_NOT_EXISTS: "User does not exist",
    CHART_NOT_EXISTS: "Chart does not exist",
    INVALID_LOGIN_REQUEST: "Invalid Email or Password",
    INVALID_CAPTCHA: "Invalid Captcha",
    UNAUTHORIZED_REQUEST: "Unauthorized Access",
    INVALID_TOKEN: "Invalid Token",
    INVALID_REQUEST: "Invalid Request",
    ROLE_NOT_EXISTS: "Role does not exist",
    ADMIN_EXISTS: "Admin already exists",
    CHART_EXISTS: "Chart already exists",
    CLIENT_EXISTS: "Client already exists",
    CLIENT_NOT_EXISTS: "Client does not exist",
    INVALID_OLD_PASSWORD: "Invalid old password",
    USER_EXISTS: "User already exists",
    TOPIC_EXISTS: "Topic already exists",
    USER_NOT_EXISTS: "User does not exist",
    TOPIC_NOT_EXISTS: "Topic does not exist",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    INVALID_IMAGE_DATA: "Invalid image data",
    USER_ALREADY_EXISTS: "User already exists",
    INVALID_PARAMETER_REQUEST: "Your request doesn't have valid parameters.",
    ROLE_ASSIGNED_TO_ADMIN: "This role is assigned and cannot be deleted",
    ALGORITHM_NOT_EXISTS: "Algorithm does not exist",
    INVALID_CODE: "Invalid code added",
    EXPIRED_CODE: "Code has expired",
    PLAN_NOT_EXISTS: "Invalid plan selected",
    SUBSCRIPTION_NOT_EXISTS: "Subscription does not exist",
    INVOICE_NOT_EXISTS: "Invoice does not exist",
    CHART_CATEGORY_EXISTS: "Chart category already exists",
    CHART_CATEGORY_NOT_EXISTS: "Chart category does not exist",
    EMAIL_NOT_FOUND: "This email address does not exist",
    INVALID_OTP: "Please enter a valid otp",
    VAT_EXISTS: "Tax already exists for selected country",
    VAT_NOT_EXISTS: "Tax does not exist",
    INACTIVE_SUBSCRIPTION: "Subscription in inactive or expired",
    CHARTS_AVAILED: "You have already added maximum number of charts available for your subscription",
    USER_CHART_EXISTS: "You have already added this chart. Please select another chart",
    ALGORITHMS_AVAILED: "You have already added maximum number of algorithms available for your subscription",
    USER_CHART_NOT_EXISTS: "Invalid Request",
    ACTIVE_CHARTS_AVAILED: "You have already activated maximum number of charts available for your subscription",
    RECEIVE_SIGNALS_AVAILED: "You have already used maximum number of signals available for your subscription",
    INDICATOR_EXISTS: "Indicator already exists",
    INDICATOR_NOT_EXISTS: "Indicator does not exist",
    SUBJECT_EXISTS: "Subject already exists",
    SUBJECT_NOT_FOUND: "Subject not found",
    TOPIC_NOT_FOUND: "Topic not found",
    NO_SUBJECTS_TO_DELETE: "No subjects selected for deletion",
    NO_TOPICS_TO_DELETE: "No topic selected for deletion",
    CATEGORY_EXISTS: "Category already exists",
    CATEGORY_NOT_FOUND: "Category not found",
    INVALID_IDS:"Invalid Ids",
    QUESTION_EXISTS: "Question already exists",
    QUESTION_NOT_FOUND: "Question not found",
    NO_QUESTIONS_TO_DELETE: "No Question selected for deletion",
    NO_IDS_PROVIDED: "No Ids Provided",
    COURSE_EXISTS: "Course already exists",
    COURSE_NOT_FOUND: "Course not found",
    NO_COURSES_TO_DELETE: "No Course selected for deletion",
    PLAN_EXISTS: "Plan already exists",
    PLAN_NOT_FOUND: "Plan not found",
    NO_PLANS_TO_DELETE: "No plan selected for deletion",
};

export const SUCCESS_MESSAGE = {
    STUDENT_DASHBOARD: "Student Dashboard Fetched successfully",
    TEACHER_DASHBOARD: "Teacher Dashboard Fetched successfully",
    CORDINATOR_DASHBOARD: "Cordinator Dashboard Fetched successfully",
    ROLE_ADDED: "Role added successfully",
    ROLE_CREATED: "Role created successfully",
    ROLES_FETCHED: "Roles fetched successfully",
    ROLE_FETCHED: "Role fetched successfully",
    ROLE_UPDATED: "Role updated successfully",
    ROLE_DELETED: "Roles deleted successfully",
    CONTACT_ADDED: "Contact added successfully",
    CONTACT_CREATED: "Contact created successfully",
    CONTACTS_FETCHED: "Contacts fetched successfully",
    CONTACT_FETCHED: "Contact fetched successfully",
    CONTACT_UPDATED: "Contact updated successfully",
    CONTACT_DELETED: "Contacts deleted successfully",
    PERMISSION_ADDED: "Permission added successfully",
    PERMISSION_CREATED: "Permission created successfully",
    PERMISSIONS_FETCHED: "Permissions fetched successfully",
    PERMISSION_FETCHED: "Permission fetched successfully",
    PERMISSION_UPDATED: "Permission updated successfully",
    PERMISSION_DELETED: "Permissions deleted successfully",
    COURSE_ADDED: "Course added successfully",
    COURSE_CREATED: "Course created successfully",
    COURSES_FETCHED: "Courses fetched successfully",
    COURSE_FETCHED: "Course fetched successfully",
    COURSE_UPDATED: "Course updated successfully",
    COURSE_DELETED: "Courses deleted successfully",
    PLAN_ADDED: "Plan added successfully",
    PLAN_CREATED: "Plan created successfully",
    PLANS_FETCHED: "Plans fetched successfully",
    PLAN_FETCHED: "Plan fetched successfully",
    PLAN_UPDATED: "Plan updated successfully",
    PLAN_DELETED: "Plans deleted successfully",
    QUESTION_ADDED: "Question added successfully",
    QUESTION_CREATED: "Question created successfully",
    QUESTIONS_FETCHED: "Questions fetched successfully",
    QUESTION_FETCHED: "Question fetched successfully",
    QUESTION_UPDATED: "Question updated successfully",
    QUESTIONS_DELETED: "Questions deleted successfully",
    SUBJECT_CREATED: "Subject created successfully",
    SUBJECTS_FETCHED: "Subjects fetched successfully",
    SUBJECT_FETCHED: "Subject fetched successfully",
    SUBJECT_UPDATED: "Subject updated successfully",
    SUBJECTS_DELETED: "Subjects deleted successfully",
    TOPIC_CREATED: "Topic created successfully",
    TOPICS_FETCHED: "Topics fetched successfully",
    TOPIC_FETCHED: "Topic fetched successfully",
    TOPIC_UPDATED: "Topic updated successfully",
    TOPICS_DELETED: "Topics deleted successfully",
    CATEGORY_CREATED: "Category created successfully",
    CATEGORIES_FETCHED: "Categories fetched successfully",
    CATEGORY_FETCHED: "Category fetched successfully",
    CATEGORY_UPDATED: "Category updated successfully",
    CATEGORIES_DELETED: "Categories deleted successfully",
    COUPONS_DELETED: "Coupon deleted successfully",
    COUPON_UPDATED: "Coupon updated successfully",
    COUPON_CREATED: "Coupon created successfully",
    COUPON_FETCHED: "Coupon fetched successfully",
    LOGGED_IN: "Logged In",
    TWO_FA_SENT: "2FA code sent successfully",
    PROFILE_UPDATED: "Profile updated successfully",
    SIGNUP_SUCCESS: "Signup successfull",
    CONTACT_SUCCESS: "Your query has been submitted successfully",
    STRIPE_SESSION_SUCCESS: "Payment link has been created successfully",
    ADMINS_FETCHED: "Admin users fetched successfully",
    ADMIN_CREATED: "Admin user created successfully",
    ADMIN_UPDATED: "Admin user updated successfully",
    ADMIN_DELETED: "Admin user moved to trash successfully",
    ADMIN_HARD_DELETED: "Admin user deleted successfully",
    ADMIN_FETCHED: "Admin user fetched successfully",
    ADMIN_RESTORED: "Admin user restored successfully",
    METRICS_FETCHED: "Dashboard metrics fetched successfully",
    PASSWORD_UPDATED: "Password updated successfully. Please sign in with new password.",
    USERS_FETCHED: "Users fetched successfully",
    USER_CREATED: "User created successfully",
    USER_UPDATED: "User updated successfully",
    USER_DELETED: "User moved to trash successfully",
    USER_HARD_DELETED: "User deleted successfully",
    USER_RESTORED: "User restored successfully",
    USER_FETCHED: "User fetched successfully",
    ALGORITHM_FETCHED: "Algorithm fetched successfully",
    ALGORITHM_CREATED: "Algorithm created successfully",
    ALGORITHM_UPDATED: "Algorithm updated successfully",
    ALGORITHM_DELETED: "Algorithm moved to trash successfully",
    ALGORITHM_HARD_DELETED: "Algorithm deleted successfully",
    ALGORITHM_RESTORED: "Algorithm restored successfully",
    ALGORITHM_CATEGORY_FETCHED: "Algorithm category fetched successfully",
    ALGORITHM_CATEGORY_ROUTES_FETCHED: "Algorithm category routes fetched successfully",
    ALGORITHM_CATEGORY_CREATED: "Algorithm category created successfully",
    ALGORITHM_CATEGORY_UPDATED: "Algorithm category updated successfully",
    ALGORITHM_CATEGORY_DELETED: "Algorithm category moved to trash successfully",
    ALGORITHM_CATEGORY_HARD_DELETED: "Algorithm category deleted successfully",
    ALGORITHM_CATEGORY_RESTORED: "Algorithm category restored successfully",
    CHARTS_FETCHED: "Charts fetched successfully",
    CHARTS_CATEGORIES_FETCHED: "Charts categories fetched successfully",
    COMPLETE_SIGNUP_PROCESS: "Please complete your signup process",
    USER_EMAIL_VERIFICATION_RESENT: "User email verification resent successfully",
    USER_EMAIL_VERIFIED: "Email verified successfully",
    USER_DETAILS_UPDATED: "Personal info updated",
    PHONE_UPDATED: "Phone number is updated",
    USER_PHONE_VERIFICATION_RESENT: "User phone verification resent successfully",
    USER_PHONE_VERIFIED: "Phone verified successfully",
    CHART_CREATED: "Chart created successfully",
    CHART_UPDATED: "Chart updated successfully",
    CHART_DELETED: "Chart moved to trash successfully",
    CHART_HARD_DELETED: "Chart deleted successfully",
    CHART_FETCHED: "Chart fetched successfully",
    CHART_SIGNALS_FETCHED: "Signals fetched successfully",
    CHART_INDICATORS_FETCHED: "Indicators fetched successfully",
    CHART_RESTORED: "Chart restored successfully",
    SUBSCRIPTION_SUCCESS: "Plan subscribed successfully",
    SUBSCRIPTION_CREATED: "Subscription created successfully",
    SUBSCRIPTIONS_FETCHED: "Subscriptions fetched successfully",
    SUBSCRIPTION_FETCHED: "Subscription fetched successfully",
    SUBSCRIPTION_DELETED: "Subscription moved to trash successfully",
    SUBSCRIPTION_RESTORED: "Subscription restored successfully",
    SUBSCRIPTION_HARD_DELETED: "Subscription deleted successfully",
    CATEGORY_ROUTES_FETCHED: "Category routes fetched successfully",
    BILLING_UPDATED: "Billing details updated successfully",
    CARD_FETCHED: "Card fetched successfully",
    CHART_CATEGORY_CREATED: "Chart category created successfully",
    CHART_CATEGORY_UPDATED: "Chart category updated successfully",
    CHART_CATEGORY_DELETED: "Chart category moved to trash successfully",
    CHART_CATEGORY_HARD_DELETED: "Chart category deleted successfully",
    CHART_CATEGORY_RESTORED: "Chart category restored successfully",
    CHART_CATEGORY_FETCHED: "Chart category fetched successfully",
    SUBSCRIPTION_PAUSED: "Subscription paused successfully",
    SUBSCRIPTION_CANCELED: "Subscription cancelled successfully",
    SUBSCRIPTION_ACTIVATED: "Subscription activated successfully",
    SUBSCRIPTION_REACTIVATED: "Subscription re-activated successfully",
    SUBSCRIPTION_UPDATED: "Subscription updated successfully",
    SUBSCRIPTION_UPGRADED: "Subscription upgraded successfully",
    SUBSCRIPTION_DOWNGRADED: "Subscription downgraded successfully",
    EMPTY_MESSAGE: "",
    FORGOT_PASSWORD_SENT: "Password reset link sent successfully.",
    PASSWORD_RESET: "Password reset successfully.",
    VATS_FETCHED: "Taxes fetched successfully",
    VAT_CREATED: "Tax created successfully",
    VAT_UPDATED: "Tax updated successfully",
    VAT_DELETED: "Tax deleted successfully",
    VAT_FETCHED: "Tax fetched successfully",
    ALGORITHM_ATTACHED: "Algorithm attached successfully",
    ALGORITHM_CHANGED: "Algorithm changed successfully",
    ALGORITHM_ACTIVATED: " is now active",
    ALGORITHM_INACTIVATED: " is now in-active",
    LOGS_FETCHED: "Activity logs fetched successfully",
    DAILY_CRON_EXECUTED: "Daily cron job ran successfully",
    MONTHLY_CRON_EXECUTED: "Monthly cron job ran successfully",
    TIMESERIES_FETCHED: "Timeseries fetched successfully",
    ONE_MINUTE_CRON_EXECUTED: "One minute cron job ran successfully",
    ALGORITHM_CONFIGURED: "Algorithm is now configured",
    SIGNAL_SENT: "Signal sent successfully",
    INDICATORS_FETCHED: "Indicators fetched successfully",
    INDICATOR_CREATED: "Indicator created successfully",
    INDICATOR_UPDATED: "Indicator updated successfully",
    INDICATOR_DELETED: "Indicator deleted successfully",
    INDICATOR_FETCHED: "Indicator fetched successfully",
    SUBSCRIPTION_VERIFIED: "Subscription verified successfully",
    TERMS_ACCEPTED: "Terms and conditions accepted successfully",
    TRADE_OPENED: "Trade opened successfully",
    TRADE_CLOSED: "Trade closed successfully",
    MARKETS_FETCHED: "Markets fetched successfully",
    TOPIC_DELETED: "Topic moved to trash successfully",
    TOPIC_HARD_DELETED: "Topic deleted successfully",
    TOPIC_RESTORED: "Topic restored successfully",
    TEST_STARTED:'Test started successfully'
};
